server:
  port: 8080
management: # actuator 环境监控 访问地址：http://localhost:8081/httptrace
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /
springfox: # swagger API接口文档 访问地址：http://localhost:8080/swagger-ui/index.html
  documentation:
    enabled: true
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
