# 构建时指定的参数变量
ARG MYSQL_VERSION=8.0.32

# 基础镜像
FROM mysql:${MYSQL_VERSION}

# 镜像维护者
MAINTAINER TuoYingtao

LABEL maintainer="TuoYingtao" description="mysql 服务" version="${MYSQL_VERSION}"

# 设置免密登录
ENV MYSQL_ALLOW_EMPTY_PASSWORD no

# 执行sql脚本
ADD /mysql/db/*.sql /docker-entrypoint-initdb.d/

# 将所需文件放到容器中
COPY ["/mysql/setup.sh", "./setup.sh"]
COPY /mysql/db/mysql.sql /mysql/mysql.sql

# 设置容器启动时执行的命令
CMD ["sh", "/mysql/setup.sh"]
